version: '3.8'

services:
  frontend1:
    build: .
    image: foll-frontend
    environment:
      - INSTANCE=Frontend1

  frontend2:
    build: .
    image: foll-frontend
    environment:
      - INSTANCE=Frontend2

  frontend3:
    build: .
    image: foll-frontend
    environment:
      - INSTANCE=Frontend3

  load-balancer:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend1
      - frontend2
      - frontend3