services:
  frontend1:
    build: .
    image: foll-frontend-1

  frontend2:
    build: .
    image: foll-frontend-2

  frontend3:
    build: .
    image: foll-frontend-3

  load-balancer:
    build:
      context: ./nginx
      dockerfile: Dockerfile.lb
    image: foll-frontend-lb:local
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - frontend1
      - frontend2
      - frontend3