events {}

http {
    # 1. Definimos el formato personalizado incluyendo la variable $upstream_addr
    log_format balanceo_logs '$remote_addr - [$time_local] "$request" '
                             'status: $status | backend_respondio: $upstream_addr';

    # 2. Le decimos a Nginx que use este formato para registrar los accesos
    access_log /var/log/nginx/access.log balanceo_logs;

    upstream frontend_servers {
        server frontend1:80;
        server frontend2:80;
        server frontend3:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://frontend_servers;
            
            add_header X-Served-By $upstream_addr always;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

    location /api/ {
                # 1. Mantenemos el proxy_pass tal cual (sin barra al final porque el back ya usa /api)
                proxy_pass https://krakend-api-gateway-54345958397.southamerica-east1.run.app;
    
                proxy_ssl_server_name on;
    
                # 2. CAMBIA ESTA LÍNEA: Forzamos a que el Host sea el dominio de Azure
                proxy_set_header Host krakend-api-gateway-54345958397.southamerica-east1.run.app;
    
                # 3. Headers estándar para propagar la IP real del cliente
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        
    }

    
}