events {}

http {
    # 1. Definimos el formato personalizado incluyendo la variable $upstream_addr
    log_format balanceo_logs '$remote_addr - [$time_local] "$request" '
                             'status: $status | backend_respondio: $upstream_addr';

    # 2. Le decimos a Nginx que use este formato para registrar los accesos
    access_log /var/log/nginx/access.log balanceo_logs;

    upstream frontend_servers {
        server frontend1:80;
        server frontend2:80;
        server frontend3:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://frontend_servers;
            
            add_header X-Served-By $upstream_addr always;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/ {
            # Nginx recibe la petición en el puerto 80 y se la pasa tal cual al Backend
            proxy_pass https://foll-backend-iot-h5hkb3czhwedhph0.brazilsouth-01.azurewebsites.net;

proxy_ssl_server_name on;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
        }
        
    }

    
}